package com.refreshme

import android.content.Context
import android.content.pm.ApplicationInfo
import android.util.Log
import com.google.firebase.FirebaseApp
import com.google.firebase.appcheck.FirebaseAppCheck
import com.google.firebase.appcheck.playintegrity.PlayIntegrityAppCheckProviderFactory
import com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory

/**
 * Initializes Firebase App Check for security.
 */
object AppCheckInitializer {

    fun initialize(context: Context) {
        // Initialize Firebase
        FirebaseApp.initializeApp(context)

        val firebaseAppCheck = FirebaseAppCheck.getInstance()
        
        val isDebuggable = (context.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE) != 0

        if (isDebuggable) {
            Log.d("AppCheck", "Using DebugAppCheckProviderFactory for local testing.")
            firebaseAppCheck.installAppCheckProviderFactory(DebugAppCheckProviderFactory.getInstance())
            // Print this to logcat explicitly to grab the secret for the Firebase Console
            Log.e("APP_CHECK_DEBUG", "Look for the debug secret generated by Firebase App Check in logcat")
        } else {
            Log.d("AppCheck", "Using PlayIntegrityAppCheckProviderFactory for production.")
            firebaseAppCheck.installAppCheckProviderFactory(PlayIntegrityAppCheckProviderFactory.getInstance())
        }
    }
}
